### ISSUE TITLE
Error: run command operation returned code=267011

### ISSUE THREAD

**Issue by Sup3rlativ3** [taliesins/terraform-provider-hyperv#42]
### Terraform Version
Terraform v0.14.4
+ provider registry.terraform.io/taliesins/hyperv v1.0.1

### Affected Resource(s)
Everything

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    hyperv = {
      source = "taliesins/hyperv"
      version = "1.0.1"
    }
  }
}

provider "hyperv" {
  user            = "domain\\myuser"
  password        = "mysupersecretpassword"
  host            = "127.0.0.1"
  port            = 5986
  https           = true
  insecure        = false
  use_ntlm        = true
  tls_server_name = ""
  cacert_path     = ""
  cert_path       = ""
  key_path        = ""
  script_path     = ""
  timeout         = "30s"
}

# Create a machine
resource "hyperv_machine_instance" "vm1" {
    name = "vm1"
    generation = 2
    state = "Running"
}
```

### Debug Output
https://gist.github.com/Sup3rlativ3/9b3fd4b6b03a8c20572530dfcf23a982

### Panic Output
none

### Expected Behavior
VM should have been created

### Actual Behavior
Nothing was created

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
Nothing

### References
The logs seem to indicate that there is a problem with the SDK being used.

```
2021/02/24 15:17:16 [WARN] Provider "registry.terraform.io/taliesins/hyperv" produced an invalid plan for hyperv_machine_instance.vm1, but we are tolerating it because it is using the legacy plugin SDK.
```

**Comment by taliesins** [comment]
I have updated plugin to use the latest version of Terraform libraries in #44 so this won't be displayed anymore

**Comment by Sup3rlativ3** [comment]
Thank you!

When will a new release be provided or it be available on the terraform registry?

**Comment by ksandrmatveyev** [comment]
Hi @taliesins ,
I'm still facing the exact error teraform 0.15 + hyperv 1.0.3
@Sup3rlativ3 was it solved for you?

**Comment by Sup3rlativ3** [comment]
I was having an issue after the update but I don't remember if it was this specific one. I haven't revisited it recently because I've moved states but will give it a shot once I get settled in.

**Comment by fsdrw08** [comment]
same issue to me, finally I change the provider user credential to a local account and fix this issue. I found this issue will happen when using microsoft account as the credential in this provider (I set the credential to my personal windows account (the microsoft account) before), seems that we should not set microsoft account / azure ad account as the user account in the provider credential config

**Comment by MODifikaTOR18** [comment]
I am having the same issue with return code 267011 when trying to create VM and VHD on a remote server. Here's my debug log: https://gist.github.com/MODifikaTOR18/3f9fca5ff5990d92ace377bcee6d515f
and terraform code:
https://gist.github.com/MODifikaTOR18/49bd687a352e0ba0dbb624a965c4dd03
I have tried to specify server's local user, but it had no effect.
